[profile.default.env]
PRIVATE_KEY_1 = { from_env = "PRIVATE_KEY_1" }
PRIVATE_KEY_2 = { from_env = "PRIVATE_KEY_2" }
ETHERSCAN_API_KEY = { from_env = "ETHERSCAN_API_KEY" }

[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
auto_detect_remappings = true # recursive auto-detection of remappings
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
